name: appwrite_dart_wrapper
description: Function Wrapper for dart_appwrite, with error handling and dependency injection.
version: 0.6.0
repository: https://github.com/Hu-Wentao/appwrite_dart_wrapper
#publish_to: "https://pub.dev"

environment:
  sdk: ">=2.17.6 <4.0.0"

# Add regular dependencies here.
dependencies:
  dart_appwrite: "^8.0.0"
  get_it: "^7.6.0"
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
